# Configuration file
version:2.1
jobs:
	my-test:
		machine:
			image: ubuntu-2005:202010-01
		steps:
			-run:			
				name: "Hello"
				command: "echo Hello"
workflow:
	hello-workflow:
	jobs:
		-my-test
